esphome:
  name: config-backup-demo
  platform: ESP32
  board: esp32dev

external_components:
  - source: github://jbdman/esphome-config-backup
    components: [ config_backup ]

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_OUT
  phy_addr: 0
  power_pin: GPIO5

web_server:
  port: 80

config_backup:
  encryption: aes256 #Encryption types for config payload accepts: none,xor,aes256 (default: none)
  key: mysecretkey #Secret for encryption/encoding
  # debug: print.b64 #Print messages for debugging accepts: print.b64,print.*,*
  # gui: True #Display the gui widget for decrypting on the web interface (default: True) !!Important Injects after ota: element right now, so won't work without ota
  # compress: True #Compress the config (prior to encrypting/encoding) (default: True)
  # config_path: /config.b64 #HTTP Path for the config blob (default: /config.b64)
