esphome:
  name: config-backup-demo
  platform: ESP32
  board: esp32dev

external_components:
  - source: github://yourgithubusername/esphome-config-backup
    components: [ config_backup ]

web_server:
  port: 80

custom_component:
  - lambda: |-
      auto backup = new ConfigBackup();
      return {backup};
